// After both builds: turns the client's shell.html into the template the server render fills in
// (dist-ssr/shell.js, read by api/render.js). The server-painted page differs from the shell in that:
// - <html data-ssr> tells main.tsx to keep the server's markup until React can paint the same thing;
// - the page's own stylesheets go in the head (<!--ssr-head-->), so the markup arrives styled;
// - the JavaScript starts after the first paint (the markup needs none to be seen), so the page's CSS
//   and fonts get the connection first; with a URL or saved season the server can't know about, the
//   markup is dropped and the app boots exactly as from the shell.
import { readFileSync, rmSync, writeFileSync } from "node:fs";

const shell = readFileSync("dist/shell.html", "utf8");
const routes = JSON.parse(readFileSync("dist/route-assets.json", "utf8"));
rmSync("dist/route-assets.json");

const take = (re) => {
  const found = [...shell.matchAll(re)];
  return { tags: found.map((m) => m[0]), values: found.map((m) => m[1]) };
};
const entry = take(/<script type="module" crossorigin src="([^"]+)"><\/script>/g);
const preloads = take(/<link rel="modulepreload" crossorigin href="([^"]+)">/g);
const routePreload = take(/<script>(\(function\(\)\{var p=location\.pathname[\s\S]*?)<\/script>/g);
const registerSw = take(/<script id="vite-plugin-pwa:register-sw" src="([^"]+)" defer(?:="")?><\/script>/g);
if (entry.values.length !== 1 || !shell.includes('<div id="root"></div>')) {
  throw new Error("ssr-shell: shell.html no longer has the expected entry script / root");
}

const boot = `(function(){var d=document.documentElement,r=document.getElementById("root"),s;
try{s=localStorage.getItem("selected_season_id")}catch(e){}
var spa=!!location.search||!!(s&&s!=="all");if(spa){r.innerHTML="";d.removeAttribute("data-ssr")}
var done=0;function go(){if(done)return;done=1;var h=document.head,p=location.pathname,f=${JSON.stringify(preloads.values)},m=${JSON.stringify(routes)},i;
for(i=0;i<m.length;i++)if(new RegExp(m[i][0]).test(p)){f=f.concat(m[i][1]);break}
f.forEach(function(u){if(/\\.css$/.test(u))return;var l=document.createElement("link");l.rel="modulepreload";l.crossOrigin="";l.href=u;h.appendChild(l)});
var e=document.createElement("script");e.type="module";e.crossOrigin="";e.src=${JSON.stringify(entry.values[0])};h.appendChild(e);
${registerSw.values[0] ? `var w=document.createElement("script");w.src=${JSON.stringify(registerSw.values[0])};w.defer=true;h.appendChild(w);` : ""}}
if(spa)return go();
try{new PerformanceObserver(function(l){if(l.getEntriesByName("first-contentful-paint").length)setTimeout(go,0)}).observe({type:"paint",buffered:true})}catch(e){}
setTimeout(go,1500)})()`;

let template = shell;
for (const tag of [...entry.tags, ...preloads.tags, ...routePreload.tags, ...registerSw.tags]) template = template.replace(tag, "");
template = template
  .replace(/<html([^>]*)>/, "<html$1 data-ssr>")
  .replace("</head>", "<!--ssr-head--></head>")
  .replace('<div id="root"></div>', `<div id="root"><!--ssr-root--></div><script>${boot.replace(/\n/g, "")}</script>`);

writeFileSync(
  "dist-ssr/shell.js",
  `// Generated by scripts/ssr-shell.mjs.\nexport const shell = ${JSON.stringify(shell)};\nexport const template = ${JSON.stringify(template)};\nexport const routes = ${JSON.stringify(routes)};\n`,
);
console.log(`ssr-shell: template with ${preloads.values.length} preloads, ${routes.length} routes`);
